version: "3.8"  # Указывает версию Docker Compose файла
services:  # Секции с сервисами (контейнерами)
  db:  # Сервис для базы данных PostgreSQL
    image: postgres:17  # Используется официальный образ PostgreSQL версии 17
    container_name: db # Явное указание контейнера для подключения бота
    restart: always  # Контейнер будет перезапускаться всегда в случае его остановки
    environment:  # Окружение для настройки контейнера
      POSTGRES_USER: ${POSTGRES_USER}  # Переменная окружения для имени пользователя базы данных
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Переменная окружения для пароля базы данных
      POSTGRES_DB: ${POSTGRES_DB}  # Переменная окружения для имени базы данных
    volumes:  # Монтирование директорий из хоста в контейнер
      # - ./data:/var/lib/postgresql/data  # Монтирование данных базы данных (постоянное хранилище)
      - postgres_data:/var/lib/postgresql/data
      - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql
      # - ./lexa_dump.sql:/docker-entrypoint-initdb.d/lexa_dump.sql  # Монтирование SQL дампа для инициализации базы данных
      # - ./postgres_data:/var/lib/postgresql/data
    ports: # Можно убрать, если используетсят только внутри докера
      - "5432:5432"  # Проброс порта базы данных, чтобы можно было подключиться с хоста
    healthcheck:  # Проверка здоровья контейнера
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]  # Проверка доступности базы данных
      interval: 10s  # Проверка каждые 10 секунд
      timeout: 10s  # Таймаут 10 секунд
      retries: 10  # Повторить 10 раз
    networks:
      - lexa_network  # Сеть, в которой будут находиться контейнеры

  bot:  # Сервис для бота (контейнер с ботом).
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: bot
    healthcheck:
      test: [ "CMD", "python", "-c", "import psycopg2; psycopg2.connect('dbname=${POSTGRES_DB} user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} host=db')" ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always  # Перезапуск контейнера всегда
    depends_on:
      db:
        condition: service_healthy  # Контейнер с ботом будет запускаться только после того, как база данных будет здоровой
    env_file:
      - .env
    environment:
      PYTHONPATH: "/app:/app/bot"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}  # Строка подключения к базе данных
    networks:
      - lexa_network  # Сеть для бота

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    networks:
      - lexa_network  # Сеть для бота

  frontend:
    build: ./frontend
    ports:
      - "80:80"  # Открываем 80 порт для доступа в браузере
    depends_on:
      - api  # Зависит от бэкенда (чтобы сначала запустился API)
    networks:
      - lexa_network  # Сеть для бота

volumes:
  postgres_data:

networks:  # Настройка сети для контейнеров
  lexa_network:
    driver: bridge  # Тип сети: bridge (основной тип сети для контейнеров)
