name: Deploy Lexa-bot to Server

on:
  push:
    branches: [ main ]

jobs:
  backup_db:
    name: Create database backup
    runs-on: ubuntu-latest
    steps:
      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Execute backup script
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            source ~/.env && \
            mkdir -p $DEPLOY_PATH/database_old && \
            docker exec $POSTGRES_HOST_CONTAINER pg_dump -U $POSTGRES_USER $POSTGRES_DB > $DEPLOY_PATH/database_old/backup_$(date +%Y-%m-%d_%H-%M-%S).sql && \
            find $DEPLOY_PATH/database_old -name '*.sql' -type f -mtime +30 -delete
          "

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy via Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            cd ${{ secrets.DEPLOY_PATH }} &&
            git config --global --add safe.directory ${{ secrets.DEPLOY_PATH }} &&
            docker-compose down && # Без -v, чтобы сохранить тома
            docker system prune -f &&
            git fetch origin &&
            git reset --hard origin/main &&
            docker-compose up --build -d
          "