name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Deploy via Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "
            cd ${{ secrets.DEPLOY_PATH }} &&
            echo 'Stopping old containers...' &&
            sudo docker-compose down -v &&
            echo 'Removing unused containers, networks, images...' &&
            sudo docker system prune -f &&
            echo 'Pulling changes from Git...' &&
            git pull origin main &&
            echo 'Building and starting new containers...' &&
            sudo docker-compose up --build -d
          "